apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webml
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - backend.yaml
  - frontend.yaml
  - gateway.yaml
  - mlflow.yaml
  - ml-service.yaml
  - networkpolicies.yaml
