apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hw2
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - backend.yaml
  - frontend.yaml
  - gateway.yaml
  - networkpolicies.yaml
