"""add user_id to request logs

Revision ID: 4da178219692
Revises: 06fcc117ed12
Create Date: 2026-05-09 20:39:20.498931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da178219692'
down_revision: Union[str, None] = '06fcc117ed12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('user_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'user_id')
    # ### end Alembic commands ###
